package com.G2T7.OurGardenStory.model;

import javax.validation.constraints.NotNull;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import java.time.*;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Ballot")

public class Ballot {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String ballotId;

    @DynamoDBAttribute
    private LocalDateTime submitDateTime;

    @DynamoDBAttribute
    private int ballotWindow;

//    private enum status{
//        FAIL,PENDING,SUCCESS,INVALID;
//    }
//
//    private Garden garden;

    public String getBallotId() {
        return ballotId;
    }
    public void setBallotId(String ballotId) {
        this.ballotId = ballotId;
    }

    @DynamoDBTypeConverted( converter = LocalDateTimeConverter.class )
    public LocalDateTime getSubmitDateTime() {
        return submitDateTime;
    }

    public void setSubmitDateTime(LocalDateTime submitDateTime) {
        this.submitDateTime = submitDateTime;
    }

    public int getBallotWindow() {
        return ballotWindow;
    }

    public void setBallotWindow(int ballotWindow) {
        this.ballotWindow = ballotWindow;
    }

    static public class LocalDateTimeConverter implements DynamoDBTypeConverter<String, LocalDateTime> {

        @Override
        public String convert( final LocalDateTime time ) {

            return time.toString();
        }

        @Override
        public LocalDateTime unconvert( final String stringValue ) {

            return LocalDateTime.parse(stringValue);
        }
    }
}
