package com.G2T7.OurGardenStory.model;

import javax.validation.constraints.NotNull;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.time.*;
import java.util.List;

@Getter
@Setter
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Ballot")

public class Ballot {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String ballotId;

    @DynamoDBTypeConverted( converter = LocalDateTimeConverter.class )
    private LocalDateTime submitDateTime;

    @DynamoDBTypeConverted( converter = LocalDateTimeConverter.class )
    private LocalDateTime leaseStart;

    @DynamoDBAttribute
    private String leaseDuration = "3Y";

    @DynamoDBAttribute
    private String status = "PENDING";

    @DynamoDBAttribute
    private int numBidsPlaced;

    @DynamoDBTypeConverted( converter = GardenConverter.class )
    private Garden garden;

    @DynamoDBTypeConverted( converter = LocalDateTimeConverter.class )
    private LocalDateTime startDateTime;

    @DynamoDBAttribute
    private String username;

    @DynamoDBAttribute
    private double distance;

    static public class GardenConverter implements DynamoDBTypeConverter<String, Garden> {
        @Override
        public String convert(final Garden garden) { return garden.toString();}

        @Override
        public Garden unconvert(final String stringValue) {
            String[] stringValueList = stringValue.split(",");
            Garden garden = new Garden();
            garden.setGardenId(stringValueList[0].substring(stringValueList[0].indexOf("=") + 1));
            garden.setLocation(stringValueList[1].substring(stringValueList[1].indexOf("=") + 1));
            garden.setName(stringValueList[2].substring(stringValueList[2].indexOf("=") + 1));
            garden.setNumPlots(Integer.parseInt(stringValueList[3].substring(stringValueList[3].indexOf("=") + 1)));
            garden.setLongitude(stringValueList[4].substring(stringValueList[4].indexOf("=") + 1));
            garden.setLatitude(stringValueList[5].substring(stringValueList[5].indexOf("=") + 1, stringValueList[5].length() - 1));
            return garden;
        }
    }

    static public class LocalDateTimeConverter implements DynamoDBTypeConverter<String, LocalDateTime> {

        @Override
        public String convert( final LocalDateTime time ) {
            return time.toString();
        }
        @Override
        public LocalDateTime unconvert( final String stringValue ) { return LocalDateTime.parse(stringValue);}
    }
}
