package com.G2T7.OurGardenStory.model;

import javax.validation.constraints.NotNull;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Garden")
public class Garden {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String gardenId;

    @NotNull(message = "Location should not be null")
    @DynamoDBAttribute
    private String location;

    @NotNull(message = "Number of plots should not be null")
    @DynamoDBAttribute
    private int numPlots;

    public String getGardenId() {
        return gardenId;
    }

    public void setGardenId(String gardenId) {
        this.gardenId = gardenId;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public int getNumPlots() {
        return numPlots;
    }

    public void setNumPlots(int numPlots) {
        this.numPlots = numPlots;
    }
}
