package com.G2T7.OurGardenStory.model;

import javax.validation.constraints.NotNull;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

@Getter
@Setter
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Garden")
public class Garden {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String gardenId; //not needed. Identified by PK

    @NotNull(message = "Location should not be null")
    @DynamoDBAttribute
    private String location; //change to address

    @NotNull
    @DynamoDBAttribute
    private String name; //gardenName

    @NotNull(message = "Number of plots should not be null")
    @DynamoDBAttribute
    private int numPlots;

    @DynamoDBAttribute
    private String longitude;

    @DynamoDBAttribute
    private String latitude;
}
