package com.G2T7.OurGardenStory.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import java.time.*;
import java.util.List;

import lombok.*;

@Getter
@Setter
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Window")
public class Window {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String windowId;

    @DynamoDBTypeConverted(converter = Window.LocalDateTimeConverter.class)
    private LocalDateTime startDateTime;

    @DynamoDBAttribute
    private String duration;

    @DynamoDBTypeConverted(converter = Ballot.LocalDateTimeConverter.class)
    private LocalDateTime leaseStart; // derived. leaseStart = startDateTime + duration

    @DynamoDBAttribute
    private List<Garden> gardenList;

    static public class LocalDateTimeConverter implements DynamoDBTypeConverter<String, LocalDateTime> {

        @Override
        public String convert(final LocalDateTime time) {
            return time.toString();
        }

        @Override
        public LocalDateTime unconvert(final String stringValue) {
            return LocalDateTime.parse(stringValue);
        }
    }
}
