package com.G2T7.OurGardenStory.model;

import javax.validation.constraints.NotNull;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import java.time.*;
import lombok.*;

@Getter
@Setter
@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Window")
public class Window {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String windowId;

    @DynamoDBAttribute
    private LocalDateTime startDateTime;

    @DynamoDBAttribute
    private String duration;

    @DynamoDBTypeConverted( converter = Window.LocalDateTimeConverter.class )
    public LocalDateTime getStartDateTime() { return startDateTime;}

    static public class LocalDateTimeConverter implements DynamoDBTypeConverter<String, LocalDateTime> {

        @Override
        public String convert( final LocalDateTime time ) {
            return time.toString();
        }
        @Override
        public LocalDateTime unconvert( final String stringValue ) {
            return LocalDateTime.parse(stringValue);
        }
    }
}
