version: '3.0'
services:
  springbackend:
    container_name: back-end
    image: haloxil/ourgardenstory-backend:latest
    build: ./SpringBackend
    restart: always
    ports:
      - 5000:5000
  
  reactfrontend:
    container_name: front-end
    image: haloxil/ourgardenstory-frontend:latest
    build: ./ReactFrontend
    ports:
      - 3000:3000
    depends_on:
      - springbackend